### ISSUE TITLE
Reprojetar o layout

### ISSUE THREAD

**Issue by fpenha** [DicksonSilva/Smell-of-coffee#3]
Cores e reorganização dos elementos ....

**Comment by DicksonSilva** [comment]
Como sugerido, modifiquei a paleta de cores, para cores mais adequadas ao tema do site, utilizei tons de 'café' para essa atividade. 
      Na reorganização, também fiz como o sugerido, adicionei círculos com imagens(Obs.: ainda não escolhi as imagens que ficarão nos círculos, nem as cores) que ficam no centro do cabeçalho e sob esses elementos ficam pequenos textos, descrevendo/sugerindo ao usuário o que tem naquele link.
      Para o título/logo combinei duas fontes, em que uma tem menos destaque para que a outra tenha um realce maior,  para esse realce de certa palavra utilizei o 'elemento' *text-shadow* que dá um tom de 'sombreado' na palavra, ele dá um destaque, além de um tom de 'café' mais forte.
